a = float(input('напишите расход в понедельнике:'))
b = float(input('напишите расход во вторнике:'))
c = float(input('напишите расход в среду:'))
d = float(input('напишите расход в четверг:'))
e = float(input('напишите расход в пятница:'))
f = float(input('напишите расход в субботу:'))
g = float(input('напишите расход в воскресенье:'))
total_spend = (a + b + c + d + f + g)
avarage = round(total_spend / 7, 1)
print("общая сумма", total_spend)
print("всего потрачено", avarage)
